-- 코드를 입력하세요
SELECT ii.INGREDIENT_TYPE, sum(fh.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF fh inner join ICECREAM_INFO ii 
on fh.FLAVOR = ii.FLAVOR
GROUP BY ii.INGREDIENT_TYPE
ORDER BY sum(fh.TOTAL_ORDER);